.\"
.\"	This file is part of devilspie2
.\"	Copyright (C) 2011-2014 Andreas Rönnquist
.\"
.\"	devilspie2 is free software: you can redistribute it and/or
.\"	modify it under the terms of the GNU General Public License as published
.\"	by the Free Software Foundation, either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	devilspie2 is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with devilspie2.
.\"	If not, see <http://www.gnu.org/licenses/>.
.\"
.TH devilspie2 1 "19 May 2014" "Version 0.35"
.SH NAME
Devilspie2 - perform scripted actions on windows as they are created
.SH Description
.B Devilspie2
is a program that detects windows as they are created, and performs scripted
actions on them. The scripts are written in LUA, allowing a great deal of
customisation.

More details in /usr/share/doc/devilspie2.

.SH Options
.IP "--version"
Displays the version of Devilspie2.
.IP "--folder folder"
Sets the folder where the LUA scripts are loaded from.
.IP "--debug"
Shows debug information from the LUA scripts. If debug_print is used in the LUA
scripts, that output will only be printed to stdout if this option is used.
.IP "--emulate"
Emulate script behaviour. Using this option only emulates a scripts behaviour,
and doesn't affect the windows that the scripts otherwise would modify.
.IP "--wnck-version"
Show version of the libwnck used. (Only availible on GTK3 or later)
.SH Script Commands

.TP
See the README or the manual linked from the homepage for a detailed description
of the commands recognized by the LUA script.

.SH Author
.B Devilspie2
was written by Andreas Rönnquist <devilspie2@gusnan.se>, and is based on Devilspie
by Ross Burton.
